### ISSUE TITLE
Where is the Sketch folder?

### ISSUE THREAD

**Issue by rar0n** [Calsign/APDE#111]
Trying to locate the Sketch folder (newly installed, only ran a few examples).

Changed Sketchfolder location in Settings from:
 Primary External
 /storage/emulated/0 

To:

Internal
/data/user/0/com.calsignlabs.apde/app_sketchbook

Or at least apparently. The last folder in /storage/emulated/0 doesn't exist, doesn't seem to be created, or show in file browser (older ES file browser). Same with the latter folder except for the /data folder, which shows but it's empty. Or contents hidden. idk. Inaccessible anyway.

Going to the copied example sketch's (SineWave) Sketch Properties shows its Sketch Folder as greyed out:
https://imgur.com/wGX24uz

**Comment by dzaima** [comment]
You'd need root to view the `/data/` folder, so you want to keep the sketch folder in `/storage/emulated/0/`. The "Location on External Storage" setting should give you the name of the sketchbook folder (for me it's at `/storage/emulated/0/Sketchbook`).

**Comment by rar0n** [comment]
Thanks for replying. Finally found it by changing it back to the `/storage/emulated/0` in APDE settings.

But it's not in that folder, for me it's in `/sdcard/Sketchbook`. The "sdcard" folder does have a small arrow by it, indicating a link I think, so I don't actually know where it is, but as long as I get access to it I don't care. I'm not sure how I missed that earlier. 

My phone doesn't actually have any external SD card anyway (not sure if that's relevant).
