### ISSUE TITLE
compiler not working

### ISSUE THREAD

**Issue by SERDUSSS** [Calsign/APDE#118]
when i try to run the sketch in preview or app apde tries to compile but it never does i found that in my friends phone it does work while he is using MIUI 11 and im using MIUI 12 the console output:

Initializing build sequence…
Deleted old build folder
Injected log broadcaster
Detected architecture arm64-v8a

Packaging resources with AAPT…

It does never compile and can stay like that for hours, i tried many diferent sketches but no code works and i tries to reinstall apde many times but same problem

**Comment by readman999** [comment]
Previously, the same thing happened after the update,
I think it was fixed by deleting the cache of the app instead of reinstalling.

Currently, the latest version is running on Redmi 9T (MIUI 12.5.7 Global).
I'm reading it in translation, so I'm sorry if it's misplaced.
(Google translate)
