### ISSUE TITLE
manage llibraries menu option force closes app

### ISSUE THREAD

**Issue by tomjuggler** [Calsign/APDE#12]
Going to tools - manage libraries force closes the app every time. I am unable to add libraries as a result. On kitkat.

**Comment by Calsign** [comment]
This bug has been present for a long time, and it was only just now that I realized what causes it. APDE crashes when you try to open the "Manage Libraries" screen from an example, but not from Import Library > Manage Libraries from a sketch. As a temporary workaround, you can open the library manager from a sketch (that is, a sketch that you can edit, not an example).

I have pushed a commit (c2a9deb75295cf625b8220f4c78cbdc1d540baff) resolving this issue. The fix will be included in the next release.

**Comment by Calsign** [comment]
The next release is currently available from the [preview channel](https://plus.google.com/communities/117703520591262292626).
