### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by automatischa** [Calsign/APDE#14]
If this uses Java, why is it not possible to code a hello world app?!

**Comment by Calsign** [comment]
What issue do you experience with a simple Hello World program? Please keep in mind that this is Processing, so program structure is simplified from Java a great deal, especially at this scale. See the [Processing.org overview page] (https://processing.org/tutorials/overview/), for example.

To print "Hello World" to the console, simply use the following line of code:

    println("Hello, World!");

If you run into other issues not explained by this, such as not being able to run any code (the examples), then you have probably found a bug, but you will need to provide more information.

**Comment by automatischa** [comment]
I knew it, but probably ran into problems because of a typo. Though, i tried your simple code but all i get is a blank app and when running it i just get a plain grey screen

Von meinem Sony Xperia™-Smartphone gesendet

---- William Smith schrieb ----

What issue do you experience with a simple Hello World program? Please keep in mind that this is Processing, so program structure is simplified from Java a great deal, especially at this scale. See the [Processing.org overview page] (https://processing.org/tutorials/overview/), for example.

To print "Hello World" to the console, simply use the following line of code:

    println("Hello, World!");

If you run into other issues not explained by this, such as not being able to run any code (the examples), then you have probably found a bug, but you will need to provide more information.

---

**Comment by Calsign** [comment]
Printing to the console will not produce any visual output; it only writes text to System.out, which will show up in the console when you return to APDE. This is the expected behavior.

Seeing as this is not an issue, I am closing it.
