### ISSUE TITLE
Can't run an app made with a contributed library

### ISSUE THREAD

**Issue by frischio46** [Calsign/APDE#19]
Hi, i need to make an Android version of a desktop processing sketch implementing the Beads audio library. So i manually installed it by following the <a href = "https://github.com/Calsign/APDE/wiki/Installing-Contributed-Libraries">tutorial</a> contained in the GitHub wiki and the only trouble i had was not being able to dex the tool.jar library via the DX Dexer.
So after building and running the app of the first example of the library, it immediately crashes and an error appears on the console:

java.lang.NoClassDefFoundError: javax.sound.sampled.AudioFormat

Is there any attempt i can do to make the library work or is it just incompatible?

**Comment by SimpleProgrammer** [comment]
In my opinion the needed class definitions are missing in the android version. See this link for details:
[javax not imported in android](http://stackoverflow.com/questions/16803343/javax-cannot-be-imported-in-my-android-app). In the link a workaround was mentioned (build jar file for the missing classes), but it was to much work for me. Also i did not know, if this really works for the sound specific classes in javax.

I used SoundPool and MediaPlayer instead. Both are supported on android.
