### ISSUE TITLE
Want to use JSON

### ISSUE THREAD

**Issue by shirish47** [Calsign/APDE#20]
I am using Processing parseJsonObject(String)
it does not work for android. I tried to Install anothe Json lib for processing into android bt it showed improperly formatted library. somthing like that... 

This one I tried. zip.

**Comment by dzaima** [comment]
Instead of parseJsonObject(), use JSONObject.parse(). Same goes for arrays. Loading and saving - use loadStrings() and join the array together and JSONObject.parse() that.

**Comment by shirish47** [comment]
I don't remember how I managed it then. but thanks anyway 👍

**Comment by dzaima** [comment]
that was mostly written for other people with the same issue, and for calsign to know what to do but ok 👍

**Comment by Calsign** [comment]
This appears to have been fixed by upgrading to Android Mode 3.0.2 in v0.4.0. `parseJSONObject()` is now recognized and compiles properly. I haven't done any testing beyond this so if there are additional problems then feel free to re-open this issue.
