### ISSUE TITLE
strange sketch crash involving size(), draw() and/or fullScreen()

### ISSUE THREAD

**Issue by Reveaper** [Calsign/APDE#25]
Phone screen resolution: 480x854
Phone: HUAWEI Y625-U51
Android version: 4.4.2
APDE  version: 0.4.0

 When I compile my sketch in APDE,  it succeeds but when I run the sketch after then it crashes while only having "void setup()" and a size(480,854) within the setup.
I like to make clear it is the sketch that stops working after it is installed - it is not APDE that crashes.

 When the sketch starts it gives me a notification that it stopped working and APDE gives me a "java.lang.NullPointerException" type of errror. Some of the error lines mention PGraphics,  background and (unknown source).

 I did a quick experiment and I will list them from first to last:
 - void setup & size(480,854) = crashed
 - void setup & size(470,844) = did not crash
 - void setup & size(470,844) + void draw() & background(0) = crashed
 - void setup & size(400,800) + void draw & background(0) = did not crash
 //end of tests

I got a handy tip to use fullScreen(); in the meantime, which appeared to work the first time I compiled my sketch. However, it crashed my sketch again and I tried a new sketch with only having a void setup & fullScreen(); and it also crashed my sketch.

 for some reason when I continue coding,  it will crash unless I reduce my size() again. 
 I still have 2 sketch apps installed from before the update and those work fine (size(480,854)). I can't find their sketch files though so I can't compile them to see if these crash now.

**Comment by Calsign** [comment]
@Reveaper I was able to reproduce this bug once when you first emailed me but have had difficulty reproducing it again. By any chance do you have a copy of the error message and stack trace? Or are you able to replicate the bug to obtain a new copy?

**Comment by Reveaper** [comment]
I can replicate the bug at will, it occurs every time when compiling with fullscreen(); or when my size(); is too big for some odd reason. 

This is the errors I get in APDE after my app crashes:
java.lang.NullPoiunterException
 at processing.core.PGraphicsAndroid2D.BackgroundImpl(Unknown Source)
 at processing.core.PGraphics.backgroundFromCalc(Unknown Source)
 at processing.core.PGraphics.background(Unknown Source)
 at processing.core.PGraphics.defaultSettings(Unknown Source)
 at processing.core.PGraphics.checkSettings(Unknown Source)
 at processing.core.PGraphicsAndroid2D.beginDraw(Unknown Source)
 at processing.core.PApplet.handleDraw(Unknown Source)
 at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
 at processing.core.PApplet.run(Unknown Source)
 at java.lang.Thread.run(Thread.java:841)

**Comment by Calsign** [comment]
Thank you.

**Comment by Calsign** [comment]
@Reveaper Try using the P2D renderer, as in:

```processing
size(480, 854, P2D);
```

**Comment by Reveaper** [comment]
using P2D succesfully launches the sketch, however the framerate is decreased significantly (my sketch operated around 1 or 2 frames per second while having a frameRate(60); in the sketch).

I would like to say that fullScreen(OPENGL); works perfectly, I have never expierenced a crash with this command. (I did encounter crashes with a blank fullScreen(); though). frameRate works fine with this command.

**Comment by Calsign** [comment]
This looks to be the same issue as [#253 in processing-android](https://github.com/processing/processing-android/issues/253), so we will have to wait for them to fix it.

It is good to know that OPENGL works while maintaining performance. Please let me know if this workaround produces and any side-effects - if not then I will close this issue and delegate to the Android mode developers.

**Comment by Reveaper** [comment]
I have not expierenced any side-effects when using fullScreen(OPENGL); and I have used this function for about a month.

 Though I do not really know the differences between fullScreen() and fullScreen(OPENGL), using OPENGl seems to work as it should without any additional complications.

**Comment by Calsign** [comment]
Using `OPENGL` as the renderer in `size()` or `fullScreen()` appears to be the workaround until the underlying problem is fixed in Android mode, so I am closing this issue.
