### ISSUE TITLE
Size fails at runtime for non-native orientations 

### ISSUE THREAD

**Issue by Techy4198** [Calsign/APDE#29]
Using some very simple code I experienced a strange issue.
```
void setup(){
  size(displayWidth, displayHeight);
}
void draw(){
}
```
When running with orientation set to portrait or unlocked while holding the phone portrait, it compiles and runs fine (blank screen as expected, no errors). But when trying landscape or reverse landscape it gives the "IllegalStateException: size() cannot be used here" error at runtime.

**Comment by Techy4198** [comment]
Okay so interestingly it also does it if I hardcode the numbers to 1920 and 1080 as reported by the variables, but if width is anything other than 1920, either above or below, then no crash occurs (other than the occasional drawing-based crashes from that other report). Height seems to have no effect at all.
Strange that this would happen, and even stranger that it triggers a seemingly unrelated crash message.

**Comment by Techy4198** [comment]
Well this gets stranger by the minute. If I actually do put size in settings(), displayWidth is reported as 1794, which is the available width not taken by the nav bar. Shouldn't this also be the case when used in (or automatically moved from) setup? Note that this bit isn't dependent on orientation. There are certainly several issues at play here but I don't entirely know how to separate them.

**Comment by Calsign** [comment]
@Techy4198 Try using the P2D renderer, as in:

```processing
size(displayWidth, displayHeight, P2D);
```

**Comment by Calsign** [comment]
@Techy4198 This is probably the same issue as #25.

See the [latest comment](https://github.com/Calsign/APDE/issues/25#issuecomment-282572066) for a potential workaround using OPENGL instead of P2D to avoid the lagginess of P2D. If this works for you as well then I will close this issue as a duplicate.

**Comment by Techy4198** [comment]
Oh wow, I knew I'd seen something similar but when I checked I must've been to tired to see it, sorry for the duplicate report.

**Comment by Techy4198** [comment]
Actually, scratch that. That report seems to focus on portrait sizes but I only ever see a crash when rotated to landscape. Haven't tested OpenGL renderer yet.
