### ISSUE TITLE
After installing the library, it doesn't appear in "Library Manager"

### ISSUE THREAD

**Issue by MilkiMilkoso** [Calsign/APDE#30]
Hello, I've already installed the library in " Install Compressed Library", but even after installing it, the Libraries folder is still empty !!! Please help

**Comment by Calsign** [comment]
What library is this? Does the same problem occur for other libraries?

Which libraries folder is empty - the one in APDE or the one in the filesystem? If the library has no examples then it will not appear in the sketch load drawer, but it should still show up under "Import Library".

**Comment by MilkiMilkoso** [comment]
Hello, I've tried to import the ketai library and the video library. The "Import Library" folder is empty, and when I click on "Manage Libraries", the "Library Manager" is also empty. When I click on "Install Compressed Library" and select the .zip file, it says that " The requested library has already been installed ", so I don´t know why it isn't appearing. I can't find any video on the internet of someone intalling a library in APDE, so I really don´t know what I'm doing wrong.

**Comment by Calsign** [comment]
The library must be in the libraries folder on the file system, but it isn't formatted correctly or something. You'll need to delete it - navigate to path/to/Sketchbook/libraries and delete the folder "Ketai". Now you can try [installing the library manually](https://github.com/Calsign/APDE/wiki/Installing-Contributed-Libraries#manual-installation). If the manual installation fails, then there might be a bug somewhere.

**Comment by MilkiMilkoso** [comment]
Omg !!! I unistalled theese libraries and I installed them againg, and somehow now it's working perfectly !!!
Thank you very much for your help.
