### ISSUE TITLE
Auto save feature deletes current tab code

### ISSUE THREAD

**Issue by TheWithz** [Calsign/APDE#31]
Google Pixel C
version 0.4.0
Android 7.1.2
landscape mode (since it's a tablet)
turning auto-save off appeared to help but I havn't tested it enough to say confidently that it fixed the issue. 

When using the app, if the document autosaves then the currently selected tab is wiped of any code. and because it was just saved there is no way to recover it. It only occurs 1 out of every 5 times or so however, not every single time. EDIT: added some details

**Comment by TheWithz** [comment]
at second glance this appears to be an extension of #24 though, occurs in different circumstances.

**Comment by TheWithz** [comment]
After reading #24 I noticed some differences. 
1. When my code was deleted there was NO screen rotation. Orientation was Landscape the entire time. 
2. the app is unbiased in it's murder (didnt matter what kind of code was in the current tab)
3. only the code in the current tab was deleted, the rest of the sketch remained the same.

**Comment by Calsign** [comment]
Despite some differences in the way in which this issue was reproduced, it is nevertheless a particular case of the code deletion bug in #24. As such I am closing this issue and merging it into #24.
