### ISSUE TITLE
using processing.video with APDE

### ISSUE THREAD

**Issue by kalwalt** [Calsign/APDE#35]
How to install this library?
Processing.video needs to be build with ant as described [here](https://github.com/processing/processing-video/wiki#building-the-library-from-source) 
I'm able to do with my desktop computer but how to do with a smartphone?
There is a smart procedure for installing this library?
Any help or hint will be very appreciated!
Thanks
Walter

**Comment by Calsign** [comment]
@kalwalt I had previously recommended using an alternative video library as the old video library was not supported by Android mode - see the [FAQ](https://github.com/Calsign/APDE/wiki#where-are-the-serial-network-video-or-sound-libraries) for more information.

The new video library is supposed to support Android - if not now, then eventually. I do not know its current status. I tried installing the library with APDE, but DX failed; I believe that the reason for this is that the library was compiled with Java 8 features that the version of DX used does not support. This should be fixable but I don't have time to look into it right now.

For the time being, I recommend trying the alternative linked in the FAQ above. There is probably a way to the video library to work with APDE and I will look into this in the future.

**Comment by kalwalt** [comment]
@Calsign Thank you for the answer, i can install **processing-video-android** but tha app crash at the start see https://github.com/omerjerk/processing-video-android/issues/8
Anyway thank for the help.
