### ISSUE TITLE
Feature Request: Live Wallpapers

### ISSUE THREAD

**Issue by ggblbl** [Calsign/APDE#37]
It'd be amazing if we could program our own live wallpapers like this: http://android.processing.org/tutorials/wallpapers/index.html

**Comment by Calsign** [comment]
@ggblbl Support for Android mode 4.0 features, including live wallpapers, are a planned feature. I do not have a definite time frame at the moment though.

**Comment by Calsign** [comment]
I've pushed the wallpaper build to the [preview channel](https://plus.google.com/102904142817938824524/posts/3StgatWRqYR).
