### ISSUE TITLE
Isn't apde supposed to be Java 8 ???

### ISSUE THREAD

**Issue by dolflou032** [Calsign/APDE#39]
import java.time.ZoneId; 
	       ^^^^^^^^^
The import java.time cannot be resolved

**Comment by dolflou032** [comment]
Yes but processing says it is shipped with Java 8 latest build but anyway

**Comment by dolflou032** [comment]
And How Am I Supposed to download it ?!?

**Comment by dolflou032** [comment]
Can't Import It only apde using latest distro (2.2.9)
"Error ... Poorly formated etc.."

**Comment by Calsign** [comment]
@dolflou032 The point that I was making is that the PDE doesn't support Java 7+ language features, even though it does support newer APIs like the time library.

APDE doesn't support these APIs for different reasons. I will look into sorting this out in the future but for the time being I recommend using alternatives.

**Comment by dolflou032** [comment]
java.io.FileNotFoundException: /storage/emulated/0/Sketchbook/libraries/META-INF/MANIFEST.MF (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:108)
	at com.calsignlabs.apde.contrib.ContributionManager.extractFile(ContributionManager.java:248)
	at com.calsignlabs.apde.contrib.ContributionManager.installZipLibrary(ContributionManager.java:84)
	at com.calsignlabs.apde.LibraryManagerActivity$15.run(LibraryManagerActivity.java:641)
	at java.lang.Thread.run(Thread.java:761)
Unexpected error occurred while extracting the library.

Got this stack when trying to import joda even to dex with dx dexer but always gives this error

**Comment by Calsign** [comment]
@dolflou032 In working on [android-mode-4](https://github.com/Calsign/APDE/tree/android-mode-4) support, I upgraded the android.jar library which adds support for Java 8 features including the new time library (3d60ed98524a7d48457f24b7f2452dde455f3d25). It turns out it was easier than I thought it was going to be. I will probably post a preview APK in the next week or so if you want to check it out.

**Comment by Calsign** [comment]
I've pushed the build with Java 8 libraries (including time) to the [preview channel](https://plus.google.com/102904142817938824524/posts/3StgatWRqYR).
