### ISSUE TITLE
[QUESTION] Install app from processing app

### ISSUE THREAD

**Issue by ungarscool1** [Calsign/APDE#44]
Hello, 

I want install app via my processing app. I have see "INSTALL_PACKAGE", but how i can install app from a processing app?

**Comment by EmmanuelPil** [comment]
Please don't take me wrong, but I would like to suggest to ask programming questions on the new forum here: https://discourse.processing.org/c/processing-android  This page is indicated for APDE related questions.  You have the possibilety to close the topic if you want to.

**Comment by Calsign** [comment]
Yes, this is off-topic. It looks like the discussion is continued here:

https://discourse.processing.org/t/install-app-from-processing-app/637
