### ISSUE TITLE
Walkthrough to Google Play

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#52]
(I apologize in advance if this is the wrong location to post this, still trying to understand the website lol)
Does anyone have a walkthrough or step by step process explaining how to get my sketch on APDE to the app store? I can't find anything on this specifically.

**Comment by EmmanuelPil** [comment]
https://github.com/Calsign/APDE/wiki/Exporting-as-a-Signed-Package
If this helps you can close the issue.

**Comment by Calsign** [comment]
@RaspyHarmony101 It depends on what your sketch does. In most cases, no. (If you were using the Maps API, for example, you would need to add Google Play services to your code. But most likely you aren't.)

It would be a good idea to test your sketch on a number of different devices with different screen sizes, versions of Android, etc.

**Comment by RaspyHarmony101** [comment]
Alrighty, thanks a bunch!
