### ISSUE TITLE
I can't seem to save(write to) my csv file

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#54]
I believe it is a problem with me, or in other words, my lack of understanding.

At the very bottom I have listed the main sources I followed while trying to solve this issue. If I find others I will edit those in.

Anyways, I've managed to create a csv file, add it to the data folder, load data from that file, and manipulate the data within the sketch. But I cannot seem to save a file to the data folder, or change the data that was given initially. If possible I would like resources I can read, watch, etc. in order to understand how to do this myself, but if you have example code then explanations are welcome.

If seeing my code will help then I would be happy to provide, just ask! :)

https://processing.org/reference/saveTable_.html
https://forum.processing.org/two/discussion/11693/read-and-write-to-the-same-csv-file-in-a-processing-app
https://forum.processing.org/two/discussion/7066/check-if-file-exist

**Comment by Calsign** [comment]
Android mode doesn't have a data folder the same way that the desktop does. As akenaton said in the first forum post you linked, Processing's data folder gets turned into the assets directory on Android. Android assets are readable but not writable.

You can, however, save to your app's storage folders. There is a private internal storage (guaranteed on every device) and the external storage (world-accessible). See the [Android docs](https://developer.android.com/guide/topics/data/data-storage) for more information.

You probably want something like this:
 - On first run...
 - Check to see if file exists in internal storage
 - If not, load default file from assets (data folder) and save it to internal storage
 - Use file in internal storage like normal - save and load everything there

The external storage is also an option but the internal storage is technically the preferred solution.

You should be able to do something like this:

```
File myFile = new File(getContext().getFilesDir(), "myFile.txt");
String myFilePath = myFile.getAbsolutePath();
// Load file from data folder (just like you are doing already)
// Save that data to myFile
// Use myFile for everything else
```

Your app has full control over its internal storage directory (`getContext().getFilesDir()`), including creating subfolders and executing files. However, the parent directory (`/data/data/processing.test.myapp/`) and its siblings are not writable by your app. Just keep that in mind.

Also, your app needs the `WRITE_EXTERNAL_STORAGE` permission to save to the external storage. The internal storage is accessible regardless of whether or not this permission is granted.

This is the type of thing that should be documented on the Android Processing website. It was there on the old wiki, but I didn't find it on the website after a cursory search. In lieu of better documentation, I am happy to answer any further questions you have and I might make a wiki page about this subject in the future.

**Comment by RaspyHarmony101** [comment]
This was quite beneficial, thank you! For now the only question I have is would my saveTable look like:  

saveTable(myFile, "myFile.txt"); 


Based on your example?

**Comment by Calsign** [comment]
Not quite. You have to specify the table. ([reference](https://processing.org/reference/saveTable_.html)) It would be something like this:

```
Table myTable; // assuming that you have a table object...

saveTable(myTable, myFile.getAbsolutePath());
```

**Comment by RaspyHarmony101** [comment]
Wow, thank you again, this is a major advancement for me.
