### ISSUE TITLE
[Feature Request] Disable Screen Overlay Check

### ISSUE THREAD

**Issue by ggblbl** [Calsign/APDE#59]
I really like that you've included a check that makes sure screen overlays don't hinder the installation of the APKs, but the popup really gets on my nerves sometimes.
Twilight has recently started to pause itself when it notices that I'm trying to install an APK, but it only pauses at the install screen, so now I dont have to pause it manually. 
The pre-build check, however, still sees the overlay and aborts the building process, which is really annoying because I have to turn it off before pressing the compile button (which I usually forget), click the compile button again and then turn it back on so my eyes don't burn.

What could help here is an option that disables the check for users like me, who don't have to worry about pausing the overlay or users who pause manually.

Thanks for the amazing app, by the way (this is literally my only gripe with it)!

**Comment by dzaima** [comment]
APDE isn't what does the check for screen overlays, it's Android itself. APDE just warns you about it, there's nothing it can do to make the app install while there's an overlay, sadly (AFAIK).

**Comment by ggblbl** [comment]
I think you misunderstood me, I mean the warning in APDE that alerts users that there is an overlay and that you won't be able to press the install button.
I think there needs to be an option like "Don't show again" or something for that popup.

**Comment by Calsign** [comment]
@ggblbl I didn't realize that Twilight started doing this. I will add an option to disable that message, and probably make it possible to bypass it as well.

**Comment by Calsign** [comment]
I have implemented these changes with f18a63e4f1ae8e57c1d8820dde42af9d79d37d63. I plan to release soon, but I don't know quite when yet.

**Comment by Calsign** [comment]
This change has been released in v0.5.1. Closing.
