### ISSUE TITLE
Examples of playing sound

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#60]
I've been trying to play sound in my app within APDE, but I don't know how to use anything. I have been looking at soundpool, but I jave found no examples to help me start and it's page on android.com is confusing to me. Can anyone aid me in this?

**Comment by ggblbl** [comment]
You should use a library, not the default Android methods.
https://processing.org/reference/libraries/#sound

**Comment by RaspyHarmony101** [comment]
Alrighty, after trying out like four different ones, I have found that the Casset library was successfully played sound! Thank you @ggblbl !

**Comment by RaspyHarmony101** [comment]
You are awesome, can't wait! Thank you!
