### ISSUE TITLE
Failed to build sketch previewer

### ISSUE THREAD

**Issue by antmay** [Calsign/APDE#69]
HI,
Just installed the app and loaded a simple example to test it. But building the code get "Failed to build sketch previewer"

This error appears after I chose the option to install the previewer.

Any ideas what I did wrong. 

If this is the wrong place to post this, please let me know where I might be able to get advice. 

Thanks

**Comment by EmmanuelPil** [comment]
Hi. What android version are you using. Have you tried to uninstall and reinstall the Sketch Previewer in the settings?

**Comment by Calsign** [comment]
Not enough information to debug this. Please feel free to re-open with Android version, stack trace, etc.
