### ISSUE TITLE
No bluetooth library works, despite manual install

### ISSUE THREAD

**Issue by MarquesAnderson** [Calsign/APDE#71]
Despite my attempts to install either a bluetooth or websocket library, none seem to work. I am manually installing them, and I've tried doing so within APDE as well just to see. The general error is that the import could not be found and the library's classes could not be resolved. What can I do to address this? Are there any libraries that are proven to work on APDE?

**Comment by EmmanuelPil** [comment]
I have been working with the ketai Bluetooth for quete a long time within APDE without any problems on kitkat and lollipop
