### ISSUE TITLE
Awesome project! Websockets anyone?

### ISSUE THREAD

**Issue by coderofsalvation** [Calsign/APDE#73]
Love this!
Any idea how to do websocket or webrequests?

**Comment by kfrajer** [comment]
Maybe try something like this: https://stackoverflow.com/questions/34131718/what-is-a-simple-way-to-implement-a-websocket-client-in-android-is-the-followin

If you get a demo going, then it could potentially be converted into a library. But first, check if there is a library that suits your use case and bring it to the app.
