### ISSUE TITLE
Delay text show up when changing rotation

### ISSUE THREAD

**Issue by EmmanuelPil** [Calsign/APDE#75]
When using a large file, working on code, editing many times; the text will show up slower and slower when starting app or changing rotation. With my  code, of about 2000 lines, I had a delay of 20 seconds. I found two solutions. One is reinstalling APDE,  and the other is copying the sketch and pasting outside the sketchook renaming it, and copying it to the sketchbook again.
After this it will show up fast again. 
I suspect that it has to do with the  file that keeps  track of the redoing.

**Comment by Calsign** [comment]
@EmmanuelPil The undo/redo history is preserved between sessions but deleted when you open a new sketch. Try opening a new sketch and switching back to the original sketch - that should clear the history.

Also try going to Settings > Editor > Undo/Redo and changing "Keep Entries" from "All" to a different number. By default there is no cap on history, but you can set a cap with this setting which should solve the problem.

Perhaps the default setting should be changed. Also, perhaps the code for loading undo/redo history is inefficient.
