### ISSUE TITLE
APDE crashes when I open it

### ISSUE THREAD

**Issue by Edwin-Pratt** [Calsign/APDE#80]
I have downloaded APDE yesterday because I wanted to program in Processing when I'm on break at school.

I had no issues at all yesterday. But when I went to open the app today, it kept crashing. I tried uninstalling APDE, restarting my phone, clearing the cache and data, but it keeps crashing.

My device is an Android 8.1.0 Go on Samsung J4 Core.

<sub>I've never submitted an issue about an Android app before so I am not really sure about what to include...</sub>

Stack trace:
![Screenshot_20191108-005959](https://user-images.githubusercontent.com/34472632/68435065-2f2dc280-01c3-11ea-9ad1-4c0b3279be21.jpg)

![Screenshot_20191108-010305](https://user-images.githubusercontent.com/34472632/68435256-96e40d80-01c3-11ea-9b29-0c7641cca2f5.jpg)

**Comment by dzaima** [comment]
My suggestion would be to try temporarily renaming the sketchbook folder (`android/data/com.calsignlabs.apde/files/` in some card), it's helped in a similar situation for me, though I'd expect data clearing to have fixed that too. Besides that I don't know where else would APDE persistently keep data.

**Comment by Edwin-Pratt** [comment]
I managed to fix the issue by clearing the app's data, And deleting the app's directory in `/storage/emulated/0/Android/`
