### ISSUE TITLE
Cannot git add in git manager history

### ISSUE THREAD

**Issue by ajspadial** [Calsign/APDE#82]
I want to synchronize my project with a github repo. I can reach a screen where I can see the change history, with an ADD link next to every piece of change in each file. However this add link/button does nothing.
That means I can't add, then I can't commit, then I can't push my changes, and I cannot work on my project from different devices.

Am I doing something wrong? Thank you.

**Comment by Calsign** [comment]
That's not an add button, that's saying there was a file added (it's a local diff). APDE's git tools are very very limited - the main way that you are meant to interact with it is with "take snapshot", which adds all files and commits (i.e. `git add .`). This should be what you are looking for, although unfortunately it doesn't give you fine-grained control over which changes you commit.

**Comment by ajspadial** [comment]
Thank you Calsign. Probably that's the functionality I need. The snapshot will be enough. 

Take care.
