### ISSUE TITLE
Connecting to Firebase?

### ISSUE THREAD

**Issue by RaspyHarmony101** [Calsign/APDE#85]
Is there a way to connect my sketch to Firebase? 
Looking on the instructions for Firebase, I have to download google-services.json and move it into my app module root directory. Is there a way to do this on APDE? I haven't yet seen what this might be.

**Comment by EmmanuelPil** [comment]
If Iyou are asking how to acces the assets directory; you need a rooted device and an explorer like the app "SD Maid".
Then you search for the directory "/data/data/com.calsignlabs.apde/app_build" where you can find the  assets directory along all others.
I use this for placing images or icons on android views, which are not acessible placing them in the data folder. You will need to use the ""app" mode. Not the preview!  Also in the settings, you need to go to the build page and enable "keep build folder.

**Comment by RaspyHarmony101** [comment]
Thanks! I believe I was able to move the file there. The next step would be to modify the build.gradle files to use the google json file. Does APDE have these? Looking through the files, I have not seen them. Is there an equivalent or alternative method known for completing this step?

**Comment by EmmanuelPil** [comment]
Just guessing. But I believe APDE does not use a Gradle script, rather uses it's own.
You can see how it is build enabling "global verbose output"  in general settings, and also " verbose output " in settings/build.
What do you need to change? Is putting the json file in the build folder (not assets) not working for you?

**Comment by RaspyHarmony101** [comment]
The file did go in the folder. But it's thr fact that Firebase requires an alteration to the application's Gradle script. Given that APDE doesn't seem to have it, I imagine the connection cannot be made. For the time being I will close this issues
