### ISSUE TITLE
New restructured oscP5 library

### ISSUE THREAD

**Issue by EmmanuelPil** [Calsign/APDE#86]
I generated the missing dex.jar and also included a new example.

You can download  it [here](https://drive.google.com/open?id=1P8NmTRCQywYxGnuhc42LTW6HNXL8V82J).

**Comment by Calsign** [comment]
This work is useful and appreciated, but I'd prefer to keep the issues page to just issues. So feel free to make a wiki page or use the Processing Forum or something, but I'm going to close this issue.
