### ISSUE TITLE
Instant crash on One UI 2.1 , Android 10

### ISSUE THREAD

**Issue by carmatic** [Calsign/APDE#89]
I am a Galaxy Tab S6 user and ever since I updated to Android 10, APDE instantly quits upon start.

**Comment by Calsign** [comment]
@carmatic I think I see your crash in the developer console. Just out of curiosity, what kind of storage does your device have? I.e., do you have an SD card? Also, is the external storage permission granted to APDE?

Anyway, I have a potential fix with 4597902cb2e663cb95a869f096978af081b82629. I am curious what choices you see in Settings > General > Sketchbook Location with the fix in place (there should be one that says "Failed to stat FS"?).

I am also getting ready to push a new release, v0.5.2, and I rolled the potential fix into the first pre-release, so if you would like the potential fix then please install [v0.5.2-pre1](https://github.com/Calsign/APDE/releases/tag/v0.5.2-pre1-alpha). (I will also be pushing to the open beta on Google Play soon if you prefer that.)

Please check out the fix, I am curious what's going on with your file systems!

**Comment by EmmanuelPil** [comment]
I´m so glad to hear this. Great!
