### ISSUE TITLE
Q: Cleanup temporary sketch folder? 

### ISSUE THREAD

**Issue by uheinema** [Calsign/APDE#93]
Hallo again,

before switching to the new release, I decided to check my temporary sketches just in case I left something usable there. 
(It will be a complete reinstall, as I have been modifying templates, see #84 )
OK, so I 'Delete sketch' on the empty ones, which happen to be created now and then...
Unfortunately, each time I do this a new eg. sketch_20200523g ... is created.
Is there a way to get rid of those (Delete ? Dont show empty sketches?)

Sorry if that is alrady fixed,, and just noticed, as I don't use temporary sketches normaly

Best regards

**Comment by Calsign** [comment]
APDE requires there to always be an active sketch, so when you delete the current sketch, a new temporary one is created in its place. Perhaps this isn't the best way for things to work, but it is how it works right now.

That being said, you can also delete any sketch from the sketch drawer. You can long-press and drag it to the trash can icon at the bottom of the screen. This way you can delete all of the temporary sketches one by one if you want to. (Note that the dragging may only work on Android 5.0+, so if you are on KitKat you may be out of luck.)

**Comment by uheinema** [comment]
#### Cool!

Never realized I could longpress there, works.

Meanwhile, I came to the conclusion that temporary sketches are a relict from non-Android envirinments.

They just don't make much sense in (unaccessible) temporary/internal storage, think of
- Show sketch folder...
- Add file ...

Can't we just remove the whole stuff and create new sketches in the Sketchbook? Running APDE without external permission would not(?) work anyhow...or not make too much sense.

Ttfn

**Comment by uheinema** [comment]
Sorry for this PS, but...
#### Lol..
Tried to continue my cleanup ...
- Ah, an empty sketch! (They get created when I rename the sketch folder outside of APDE with it still runnng(more/worse on this later) or this being the last sketch used. Explained above, it's a feature....). 
- So: Top right, longpress, trash...
- Oops, another new empty sketch gets created (Explained above.....)

Lol...

OK, I will 
- Identify&Copy those (1½?) sketches I want to keep to the Sketchbook.
- Go there amd delete all remaining (Superflous, I'll reinstall anyhow)
...

Still grinning...

Close after noticing.

**Comment by EmmanuelPil** [comment]
> if you are on KitKat you may be out of luck.

It does drag delete on this version as well on Kitkat 4.4.
Still sketches can be removed on a rooted device at "/data/data/com.calsignlabs.apde/" etc.
If it's of interest for someone, there is also where I access my assets folder of the build, to set images on views.
